### PR TITLE
Move target user into the table in AppItem

### PR DESCRIPTION
**Pull request by dmnd**
[As described on Asana](https://app.asana.com/0/1173169863329737/1173169863329787)

### CODE REVIEW

**Comment by ytsheng** [comment]
Looks good with me!

**Comment by ytsheng** [comment]
Do you mind making the changes in our scripts as well? We use a script to generate our website since it is static right now. For details, refer to the onboarding doc. :) We can merge after the scripts is modified as well!

**Comment by dmnd** [comment]
> Do you mind making the changes in our scripts as well?

I'm probably misunderstanding, but this change is unobservable to `<AppList />` and so I think there doesn't need to be any updates to that the code that generates `<AppList />`. If I'm mistaken, can you point me at a line that needs updating?

**Comment by ytsheng** [comment]
Ah you are right!!

**Comment by ytsheng** [comment]
Merging your changes!!!

**Pull request merged**
